/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TeamId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TournamentId = IDL.Nat;
export const Tournament = IDL.Record({
  'id' : TournamentId,
  'status' : IDL.Variant({
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  }),
  'venue' : IDL.Text,
  'name' : IDL.Text,
  'upiId' : IDL.Text,
  'maxTeams' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'adminNotes' : IDL.Text,
  'startDate' : IDL.Text,
  'format' : IDL.Variant({ 'roundrobin' : IDL.Null, 'knockout' : IDL.Null }),
});
export const MatchId = IDL.Nat;
export const Match = IDL.Record({
  'id' : MatchId,
  'result' : IDL.Opt(IDL.Text),
  'winnerId' : IDL.Opt(TeamId),
  'team1Id' : TeamId,
  'team2Id' : TeamId,
  'roundNumber' : IDL.Nat,
  'tournamentId' : TournamentId,
});
export const Team = IDL.Record({
  'id' : TeamId,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'teamName' : IDL.Text,
  'captainName' : IDL.Text,
  'upiNote' : IDL.Text,
  'players' : IDL.Vec(IDL.Text),
  'phoneNumber' : IDL.Text,
  'tournamentId' : TournamentId,
  'slotNumber' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveTeam' : IDL.Func([TeamId, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTournament' : IDL.Func([Tournament], [TournamentId], []),
  'deleteTournament' : IDL.Func([TournamentId], [], []),
  'generateKnockoutFixtures' : IDL.Func([TournamentId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchesByTournament' : IDL.Func(
      [TournamentId],
      [IDL.Vec(Match)],
      ['query'],
    ),
  'getTeamsByStatus' : IDL.Func(
      [
        TournamentId,
        IDL.Variant({
          'pending' : IDL.Null,
          'approved' : IDL.Null,
          'rejected' : IDL.Null,
        }),
      ],
      [IDL.Vec(Team)],
      ['query'],
    ),
  'getTeamsByTournament' : IDL.Func([TournamentId], [IDL.Vec(Team)], ['query']),
  'getTournamentById' : IDL.Func(
      [TournamentId],
      [IDL.Opt(Tournament)],
      ['query'],
    ),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerTeam' : IDL.Func([TournamentId, Team], [TeamId], []),
  'rejectTeam' : IDL.Func([TeamId], [], []),
  'setMatchResult' : IDL.Func([MatchId, IDL.Text, TeamId], [], []),
  'updateTournament' : IDL.Func([TournamentId, Tournament], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TeamId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TournamentId = IDL.Nat;
  const Tournament = IDL.Record({
    'id' : TournamentId,
    'status' : IDL.Variant({
      'upcoming' : IDL.Null,
      'completed' : IDL.Null,
      'ongoing' : IDL.Null,
    }),
    'venue' : IDL.Text,
    'name' : IDL.Text,
    'upiId' : IDL.Text,
    'maxTeams' : IDL.Nat,
    'entryFee' : IDL.Nat,
    'adminNotes' : IDL.Text,
    'startDate' : IDL.Text,
    'format' : IDL.Variant({ 'roundrobin' : IDL.Null, 'knockout' : IDL.Null }),
  });
  const MatchId = IDL.Nat;
  const Match = IDL.Record({
    'id' : MatchId,
    'result' : IDL.Opt(IDL.Text),
    'winnerId' : IDL.Opt(TeamId),
    'team1Id' : TeamId,
    'team2Id' : TeamId,
    'roundNumber' : IDL.Nat,
    'tournamentId' : TournamentId,
  });
  const Team = IDL.Record({
    'id' : TeamId,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'teamName' : IDL.Text,
    'captainName' : IDL.Text,
    'upiNote' : IDL.Text,
    'players' : IDL.Vec(IDL.Text),
    'phoneNumber' : IDL.Text,
    'tournamentId' : TournamentId,
    'slotNumber' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveTeam' : IDL.Func([TeamId, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTournament' : IDL.Func([Tournament], [TournamentId], []),
    'deleteTournament' : IDL.Func([TournamentId], [], []),
    'generateKnockoutFixtures' : IDL.Func([TournamentId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchesByTournament' : IDL.Func(
        [TournamentId],
        [IDL.Vec(Match)],
        ['query'],
      ),
    'getTeamsByStatus' : IDL.Func(
        [
          TournamentId,
          IDL.Variant({
            'pending' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
          }),
        ],
        [IDL.Vec(Team)],
        ['query'],
      ),
    'getTeamsByTournament' : IDL.Func(
        [TournamentId],
        [IDL.Vec(Team)],
        ['query'],
      ),
    'getTournamentById' : IDL.Func(
        [TournamentId],
        [IDL.Opt(Tournament)],
        ['query'],
      ),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerTeam' : IDL.Func([TournamentId, Team], [TeamId], []),
    'rejectTeam' : IDL.Func([TeamId], [], []),
    'setMatchResult' : IDL.Func([MatchId, IDL.Text, TeamId], [], []),
    'updateTournament' : IDL.Func([TournamentId, Tournament], [], []),
  });
};

export const init = ({ IDL }) => { return []; };