/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Match {
  'id' : MatchId,
  'result' : [] | [string],
  'winnerId' : [] | [TeamId],
  'team1Id' : TeamId,
  'team2Id' : TeamId,
  'roundNumber' : bigint,
  'tournamentId' : TournamentId,
}
export type MatchId = bigint;
export interface Team {
  'id' : TeamId,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'teamName' : string,
  'captainName' : string,
  'upiNote' : string,
  'players' : Array<string>,
  'phoneNumber' : string,
  'tournamentId' : TournamentId,
  'slotNumber' : [] | [bigint],
}
export type TeamId = bigint;
export interface Tournament {
  'id' : TournamentId,
  'status' : { 'upcoming' : null } |
    { 'completed' : null } |
    { 'ongoing' : null },
  'venue' : string,
  'name' : string,
  'upiId' : string,
  'maxTeams' : bigint,
  'entryFee' : bigint,
  'adminNotes' : string,
  'startDate' : string,
  'format' : { 'roundrobin' : null } |
    { 'knockout' : null },
}
export type TournamentId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveTeam' : ActorMethod<[TeamId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTournament' : ActorMethod<[Tournament], TournamentId>,
  'deleteTournament' : ActorMethod<[TournamentId], undefined>,
  'generateKnockoutFixtures' : ActorMethod<[TournamentId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatchesByTournament' : ActorMethod<[TournamentId], Array<Match>>,
  'getTeamsByStatus' : ActorMethod<
    [
      TournamentId,
      { 'pending' : null } |
        { 'approved' : null } |
        { 'rejected' : null },
    ],
    Array<Team>
  >,
  'getTeamsByTournament' : ActorMethod<[TournamentId], Array<Team>>,
  'getTournamentById' : ActorMethod<[TournamentId], [] | [Tournament]>,
  'getTournaments' : ActorMethod<[], Array<Tournament>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerTeam' : ActorMethod<[TournamentId, Team], TeamId>,
  'rejectTeam' : ActorMethod<[TeamId], undefined>,
  'setMatchResult' : ActorMethod<[MatchId, string, TeamId], undefined>,
  'updateTournament' : ActorMethod<[TournamentId, Tournament], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];