/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type TournamentId = bigint;
export interface Tournament {
    id: TournamentId;
    status: Variant_upcoming_completed_ongoing;
    venue: string;
    name: string;
    upiId: string;
    maxTeams: bigint;
    entryFee: bigint;
    adminNotes: string;
    startDate: string;
    format: Variant_roundrobin_knockout;
}
export interface Match {
    id: MatchId;
    result?: string;
    winnerId?: TeamId;
    team1Id: TeamId;
    team2Id: TeamId;
    roundNumber: bigint;
    tournamentId: TournamentId;
}
export type MatchId = bigint;
export type TeamId = bigint;
export interface Team {
    id: TeamId;
    status: Variant_pending_approved_rejected;
    teamName: string;
    captainName: string;
    upiNote: string;
    players: Array<string>;
    phoneNumber: string;
    tournamentId: TournamentId;
    slotNumber?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Variant_roundrobin_knockout {
    roundrobin = "roundrobin",
    knockout = "knockout"
}
export enum Variant_upcoming_completed_ongoing {
    upcoming = "upcoming",
    completed = "completed",
    ongoing = "ongoing"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveTeam(teamId: TeamId, slotNumber: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTournament(tournament: Tournament): Promise<TournamentId>;
    deleteTournament(tournamentId: TournamentId): Promise<void>;
    generateKnockoutFixtures(tournamentId: TournamentId): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getMatchesByTournament(tournamentId: TournamentId): Promise<Array<Match>>;
    getTeamsByStatus(tournamentId: TournamentId, status: Variant_pending_approved_rejected): Promise<Array<Team>>;
    getTeamsByTournament(tournamentId: TournamentId): Promise<Array<Team>>;
    getTournamentById(tournamentId: TournamentId): Promise<Tournament | null>;
    getTournaments(): Promise<Array<Tournament>>;
    isCallerAdmin(): Promise<boolean>;
    registerTeam(tournamentId: TournamentId, team: Team): Promise<TeamId>;
    rejectTeam(teamId: TeamId): Promise<void>;
    setMatchResult(matchId: MatchId, result: string, winnerId: TeamId): Promise<void>;
    updateTournament(tournamentId: TournamentId, tournament: Tournament): Promise<void>;
}
import type { Match as _Match, MatchId as _MatchId, Team as _Team, TeamId as _TeamId, Tournament as _Tournament, TournamentId as _TournamentId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveTeam(arg0: TeamId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTeam(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTeam(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTournament(arg0: Tournament): Promise<TournamentId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(to_candid_Tournament_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(to_candid_Tournament_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteTournament(arg0: TournamentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTournament(arg0);
            return result;
        }
    }
    async generateKnockoutFixtures(arg0: TournamentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.generateKnockoutFixtures(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateKnockoutFixtures(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchesByTournament(arg0: TournamentId): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchesByTournament(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchesByTournament(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamsByStatus(arg0: TournamentId, arg1: Variant_pending_approved_rejected): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamsByStatus(arg0, to_candid_variant_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamsByStatus(arg0, to_candid_variant_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamsByTournament(arg0: TournamentId): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamsByTournament(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamsByTournament(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentById(arg0: TournamentId): Promise<Tournament | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentById(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentById(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournaments();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournaments();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerTeam(arg0: TournamentId, arg1: Team): Promise<TeamId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerTeam(arg0, to_candid_Team_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerTeam(arg0, to_candid_Team_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async rejectTeam(arg0: TeamId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTeam(arg0);
            return result;
        }
    }
    async setMatchResult(arg0: MatchId, arg1: string, arg2: TeamId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMatchResult(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMatchResult(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTournament(arg0: TournamentId, arg1: Tournament): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournament(arg0, to_candid_Tournament_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournament(arg0, to_candid_Tournament_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Match_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Tournament_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tournament): Tournament {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamId]): TeamId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tournament]): Tournament | null {
    return value.length === 0 ? null : from_candid_Tournament_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MatchId;
    result: [] | [string];
    winnerId: [] | [_TeamId];
    team1Id: _TeamId;
    team2Id: _TeamId;
    roundNumber: bigint;
    tournamentId: _TournamentId;
}): {
    id: MatchId;
    result?: string;
    winnerId?: TeamId;
    team1Id: TeamId;
    team2Id: TeamId;
    roundNumber: bigint;
    tournamentId: TournamentId;
} {
    return {
        id: value.id,
        result: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.result)),
        winnerId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.winnerId)),
        team1Id: value.team1Id,
        team2Id: value.team2Id,
        roundNumber: value.roundNumber,
        tournamentId: value.tournamentId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TeamId;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    teamName: string;
    captainName: string;
    upiNote: string;
    players: Array<string>;
    phoneNumber: string;
    tournamentId: _TournamentId;
    slotNumber: [] | [bigint];
}): {
    id: TeamId;
    status: Variant_pending_approved_rejected;
    teamName: string;
    captainName: string;
    upiNote: string;
    players: Array<string>;
    phoneNumber: string;
    tournamentId: TournamentId;
    slotNumber?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n18(_uploadFile, _downloadFile, value.status),
        teamName: value.teamName,
        captainName: value.captainName,
        upiNote: value.upiNote,
        players: value.players,
        phoneNumber: value.phoneNumber,
        tournamentId: value.tournamentId,
        slotNumber: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.slotNumber))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TournamentId;
    status: {
        upcoming: null;
    } | {
        completed: null;
    } | {
        ongoing: null;
    };
    venue: string;
    name: string;
    upiId: string;
    maxTeams: bigint;
    entryFee: bigint;
    adminNotes: string;
    startDate: string;
    format: {
        roundrobin: null;
    } | {
        knockout: null;
    };
}): {
    id: TournamentId;
    status: Variant_upcoming_completed_ongoing;
    venue: string;
    name: string;
    upiId: string;
    maxTeams: bigint;
    entryFee: bigint;
    adminNotes: string;
    startDate: string;
    format: Variant_roundrobin_knockout;
} {
    return {
        id: value.id,
        status: from_candid_variant_n23(_uploadFile, _downloadFile, value.status),
        venue: value.venue,
        name: value.name,
        upiId: value.upiId,
        maxTeams: value.maxTeams,
        entryFee: value.entryFee,
        adminNotes: value.adminNotes,
        startDate: value.startDate,
        format: from_candid_variant_n24(_uploadFile, _downloadFile, value.format)
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    completed: null;
} | {
    ongoing: null;
}): Variant_upcoming_completed_ongoing {
    return "upcoming" in value ? Variant_upcoming_completed_ongoing.upcoming : "completed" in value ? Variant_upcoming_completed_ongoing.completed : "ongoing" in value ? Variant_upcoming_completed_ongoing.ongoing : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roundrobin: null;
} | {
    knockout: null;
}): Variant_roundrobin_knockout {
    return "roundrobin" in value ? Variant_roundrobin_knockout.roundrobin : "knockout" in value ? Variant_roundrobin_knockout.knockout : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Team>): Array<Team> {
    return value.map((x)=>from_candid_Team_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tournament>): Array<Tournament> {
    return value.map((x)=>from_candid_Tournament_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Team_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Team): _Team {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_Tournament_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tournament): _Tournament {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TeamId;
    status: Variant_pending_approved_rejected;
    teamName: string;
    captainName: string;
    upiNote: string;
    players: Array<string>;
    phoneNumber: string;
    tournamentId: TournamentId;
    slotNumber?: bigint;
}): {
    id: _TeamId;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    teamName: string;
    captainName: string;
    upiNote: string;
    players: Array<string>;
    phoneNumber: string;
    tournamentId: _TournamentId;
    slotNumber: [] | [bigint];
} {
    return {
        id: value.id,
        status: to_candid_variant_n14(_uploadFile, _downloadFile, value.status),
        teamName: value.teamName,
        captainName: value.captainName,
        upiNote: value.upiNote,
        players: value.players,
        phoneNumber: value.phoneNumber,
        tournamentId: value.tournamentId,
        slotNumber: value.slotNumber ? candid_some(value.slotNumber) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TournamentId;
    status: Variant_upcoming_completed_ongoing;
    venue: string;
    name: string;
    upiId: string;
    maxTeams: bigint;
    entryFee: bigint;
    adminNotes: string;
    startDate: string;
    format: Variant_roundrobin_knockout;
}): {
    id: _TournamentId;
    status: {
        upcoming: null;
    } | {
        completed: null;
    } | {
        ongoing: null;
    };
    venue: string;
    name: string;
    upiId: string;
    maxTeams: bigint;
    entryFee: bigint;
    adminNotes: string;
    startDate: string;
    format: {
        roundrobin: null;
    } | {
        knockout: null;
    };
} {
    return {
        id: value.id,
        status: to_candid_variant_n5(_uploadFile, _downloadFile, value.status),
        venue: value.venue,
        name: value.name,
        upiId: value.upiId,
        maxTeams: value.maxTeams,
        entryFee: value.entryFee,
        adminNotes: value.adminNotes,
        startDate: value.startDate,
        format: to_candid_variant_n6(_uploadFile, _downloadFile, value.format)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_approved_rejected): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == Variant_pending_approved_rejected.pending ? {
        pending: null
    } : value == Variant_pending_approved_rejected.approved ? {
        approved: null
    } : value == Variant_pending_approved_rejected.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_upcoming_completed_ongoing): {
    upcoming: null;
} | {
    completed: null;
} | {
    ongoing: null;
} {
    return value == Variant_upcoming_completed_ongoing.upcoming ? {
        upcoming: null
    } : value == Variant_upcoming_completed_ongoing.completed ? {
        completed: null
    } : value == Variant_upcoming_completed_ongoing.ongoing ? {
        ongoing: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_roundrobin_knockout): {
    roundrobin: null;
} | {
    knockout: null;
} {
    return value == Variant_roundrobin_knockout.roundrobin ? {
        roundrobin: null
    } : value == Variant_roundrobin_knockout.knockout ? {
        knockout: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
